# Generated by Django 5.2.4 on 2025-07-12 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='days',
        ),
    ]
