# Generated by Django 5.2.4 on 2025-07-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_remove_course_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='days',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], default='Monday', max_length=10),
        ),
    ]
