# Generated by Django 5.0.7 on 2024-07-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_remove_attendancereport_attendance_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='students',
            name='rollnumber',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
